---
galaxy_info:
  author: Brian Kenkel
  description: Install Git.
  license: Proprietary
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - all

dependencies: []
