---
galaxy_info:
  author: Brian Kenkel
  description: Install Backrest as a systemd service via its upstream install script.
  license: Proprietary
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - all

dependencies: []
