---
onepass_service_account__name: "{{ inventory_hostname }}"
onepass_service_account__vault: secrets
onepass_service_account__item: "{{ inventory_hostname }}.op-service-account"
onepass_service_account__vaults: []
onepass_service_account__owner: "{{ ansible_facts['user_id'] }}"
