---
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges

- name: Enable the periodic update and upgrade timers
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::AutocleanInterval "7";
    owner: root
    group: root
    mode: "0644"

- name: Limit unattended-upgrades to security origins
  ansible.builtin.template:
    src: 51-provision.conf.j2
    dest: /etc/apt/apt.conf.d/51-provision
    owner: root
    group: root
    mode: "0644"
