all:
  hosts:
    core01.home-cvg.internal:
    media01.home-cvg.internal:
    apps01.home-cvg.internal:
    edge01.vultr-ord.internal:
  children:
    bare_metal:
      hosts:
        core01.home-cvg.internal:
        media01.home-cvg.internal:
        apps01.home-cvg.internal:
    vps:
      hosts:
        edge01.vultr-ord.internal:
    control_plane:
      hosts:
        core01.home-cvg.internal:
