root = true

[providers.onepassword]
type  = "1password"
vault = "secrets"

[secrets]
TS_AUTHKEY = { provider = "onepassword", value = "tailscale.auth-key.docker-gateway-container/credential" }

[profiles.pango.secrets]
HOST = { default = "pango" }

CLIENT_ID     = { provider = "onepassword", value = "host.pango/pangolin_id" }
CLIENT_SECRET = { provider = "onepassword", value = "host.pango/pangolin_secret" }
NEWT_ID       = { provider = "onepassword", value = "host.pango/newt_id" }
NEWT_SECRET   = { provider = "onepassword", value = "host.pango/newt_secret" }

[profiles.bill.secrets]
HOST = { default = "bill" }

CLIENT_ID     = { provider = "onepassword", value = "host.bill/CLIENT_ID" }
CLIENT_SECRET = { provider = "onepassword", value = "host.bill/CLIENT_SECRET" }
NEWT_ID       = { provider = "onepassword", value = "hosts.bill.newt/NEWT_ID" }
NEWT_SECRET   = { provider = "onepassword", value = "hosts.bill.newt/NEWT_SECRET" }

[profiles.littlebuddy.secrets]
HOST = { default = "littlebuddy" }

CLIENT_ID     = { provider = "onepassword", value = "host.littlebuddy/CLIENT_ID" }
CLIENT_SECRET = { provider = "onepassword", value = "host.littlebuddy/CLIENT_SECRET" }
NEWT_ID       = { provider = "onepassword", value = "hosts.littlebuddy.newt/NEWT_ID" }
NEWT_SECRET   = { provider = "onepassword", value = "hosts.littlebuddy.newt/NEWT_SECRET" }

[profiles.paiki.secrets]
HOST = { default = "paiki" }

CLIENT_ID     = { provider = "onepassword", value = "host.paiki/CLIENT_ID" }
CLIENT_SECRET = { provider = "onepassword", value = "host.paiki/CLIENT_SECRET" }
NEWT_ID       = { provider = "onepassword", value = "hosts.paiki.newt/NEWT_ID" }
NEWT_SECRET   = { provider = "onepassword", value = "hosts.paiki.newt/NEWT_SECRET" }
