[providers]
[providers.op_ansible]
type    = "1password"
account = "FUKUXFLIDREQDELXYP2PALUAVY"
vault   = "secrets"

[secrets]
TS_AUTHKEY = { provider = "op_ansible", value = "TS_AUTHKEY/credential"}
BACKREST_KTB_BACKUP_APP_PASSWORD = { provider = "op_ansible", value = "ktb-backup-app/password" }
BACKREST_KTB_BACKUP_APP_AWS_ACCESS_KEY_ID = { provider = "op_ansible", value = "ktb-backup-app/AWS_ACCESS_KEY_ID" }
BACKREST_KTB_BACKUP_APP_AWS_SECRET_ACCESS_KEY = { provider = "op_ansible", value = "ktb-backup-app/AWS_SECRET_ACCESS_KEY" }
