#!/usr/bin/env bash
# Wrapper Script for Docker Compose Command
# Usage:
#   `./wrap docker compose up -d`
#   `./wrap docker compose down`

set -euo pipefail
set -a; . /mnt/credentials/onepassword.env; set +a
exec fnox exec -- "$@"