---
docker_stack_files__cache_dir: "{{ docker_stack_files__stacks_dir }}/_repo_cache/{{ docker_stack_files__name }}"
docker_stack_files__deploy_dir: "{{ docker_stack_files__stacks_dir }}/{{ docker_stack_files__name }}"
